# site settings
title: Jooyoung Oh
subtitle: Portfolio
email: JooyoungOh2026@u.northwestern.edu
description: Welcome to my online portfolio!<br/> Feel free to check out some of my work.
baseurl: # the subpath of your site, e.g. /blog
url: 'https://joodevs.github.io' # the base hostname & protocol for your site
author: Jooyoung Oh
street_address: https://github.com/joodevs
city:
state:
zip_code:
country:
phone: https://www.linkedin.com/in/jooyoung-oh

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/joodevs
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/7oo.oh/
  LinkedIn: https://www.linkedin.com/in/joooyoung-oh
  Twitter:
  Facebook: https://www.facebook.com/jooyoung.oh.102/z
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
